---
name: kblocks
confinement: strict
grade: stable
base: core20
adopt-info: kblocks
apps:
    kblocks:
        extensions:
        - kde-neon
        common-id: org.kde.kblocks.desktop
        command: usr/bin/kblocks
        plugs:
        - kde-frameworks-5-plug
        - home
        - network
        - network-bind
        - audio-playback
        - alsa
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kblocks
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-15-core20-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-15-core20
        target: kf5
package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
parts:
    kblocks:
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5doctools-dev
        build-environment:
        - CMAKE_BUILD_PARALLEL_LEVEL: "4"
        stage-packages:
        - libasound2-data
        - libasound2-plugins
        filesets:
            exclusion:
            - "-usr/lib/*/cmake/*"
            - "-usr/include/*"
            - "-usr/share/ECM/*"
            - "-usr/share/doc/*"
            - "-usr/share/man/*"
            - "-usr/share/icons/breeze-dark*"
            - "-usr/bin/X11"
            - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
            - "-usr/lib/aspell/*"
        prime:
        - "$exclusion"
        - "-etc/alsa/conf.d/99-pulse.conf"
        parse-info:
        - usr/share/metainfo/org.kde.kblocks.appdata.xml
        source: http://download.kde.org/stable/release-service/20.12.3/src/kblocks-20.12.3.tar.xz
        cmake-parameters:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;/root/stage\\;/snap/kde-frameworks-5-qt-5-15-core20-sdk/current"
