---
name: kblocks
version: 20.08.0
confinement: strict
grade: stable
base: core18
adopt-info: kblocks
apps:
    kblocks:
        common-id: org.kde.kblocks.desktop
        command: kf5-launch kblocks
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - desktop
        - network
        - network-bind
        - unity7
        - pulseaudio
        - desktop-legacy
        - removable-media
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kblocks
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-qt-5-14-core18-all
        interface: content
        default-provider: kde-frameworks-5-qt-5-14-core18
        target: kf5
parts:
    kblocks:
        parse-info:
        - usr/share/metainfo/org.kde.kblocks.appdata.xml
        build-snaps:
        - kde-frameworks-5-qt-5-14-core18-sdk
        after:
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - kdoctools-dev
        - libkf5kdegames-dev
        stage-packages:
        - libkf5kdegamesprivate1
        - libkf5kdegames7
        source: http://download.kde.org/stable/release-service/20.08.0/src/kblocks-20.08.0.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
        - "-DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-qt-5-14-core18-sdk/current"
    kde-frameworks-5-env:
        plugin: dump
        source: https://anongit.kde.org/snap-kf5-launcher.git
